name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3


      - name : code deploy
        uses : burnett01/rsync-deployments@5.2
        with :
          switches : -avzr --delete
          remote_path : /home/cocopam/workspace/django-actions-test/
          remote_host : cspc.me
          remote_user : cocopam
          remote_key : ${{secrets.SSH_KEY}}


      - name: docker run
        uses: appleboy/ssh-actions@master
        with:
          host: cspc.me
          username : cocopam
          key: ${{secret.SSH_KEY}}
          script: |
            sh /home/cocopam/workspace/django-actions-test/docker.sh
